# -*- coding: utf-8 -*-
"""533691_Ananda Auliya Rahma_Assignment 2 Deep Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3GW7K5A4iE1ipaWBUgHovPiX1K2u_jT

## Assignment 2 Learning Strategy: Regularization Experiments on MNIST
### Ananda Auliya Rahma (24/533691/PA/22608)

### 1. Load Data
"""

import numpy as np
import keras

(X_train, y_train_raw), (X_test, y_test_raw) = keras.datasets.mnist.load_data()

X_train = X_train.reshape(-1, 28, 28, 1).astype('float32')
X_test = X_test.reshape(-1, 28, 28, 1).astype('float32')
X_train /= 255
X_test /= 255

y_train = keras.utils.to_categorical(y_train_raw, 10)
y_test = keras.utils.to_categorical(y_test_raw, 10)

print('X_train', X_train.shape)
print('X_test', X_test.shape)

"""### 2. Baseline Model"""

from keras.models import Sequential
from keras.layers import Flatten, Dense

model1 = Sequential()
model1.add(Flatten())
model1.add(Dense(64, activation='relu'))
model1.add(Dense(10, activation='softmax'))

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
history = model1.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model1.summary()

loss, accuracy = model1.evaluate(X_test, y_test)
print('Akurasi Testing Baseline:', accuracy)

import matplotlib.pyplot as plt

loss, acc = model1.evaluate(X_test, y_test)

print('Akurasi Testing Baseline:', acc)

plt.plot(range(1, len(history.history['loss']) + 1),
         history.history['loss'], 'r', label='training loss')

plt.plot(range(1, len(history.history['val_loss']) + 1),
         history.history['val_loss'], 'b', label='validation loss')

plt.xticks(range(1, 11))
plt.xlim(1, 10)

plt.legend()
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Baseline')

plt.show()

"""### 3. Experiment A. L1 Regularization"""

from keras.regularizers import l1

L1_RATE = 0.0001

model_l1 = Sequential()
model_l1.add(Flatten())
model_l1.add(Dense(64, activation='relu', kernel_regularizer=l1(L1_RATE)))
model_l1.add(Dense(10, activation='softmax', kernel_regularizer=l1(L1_RATE)))
model_l1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

history_l1 = model_l1.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_l1.summary()

import matplotlib.pyplot as plt

loss, acc = model_l1.evaluate(X_test, y_test)
print('Akurasi Testing L1:', acc)

plt.plot(range(1, len(history_l1.history['loss']) + 1),
         history_l1.history['loss'], 'r', label='training loss')

plt.plot(range(1, len(history_l1.history['val_loss']) + 1),
         history_l1.history['val_loss'], 'b', label='validation loss')

plt.xticks(range(1, 11))
plt.xlim(1, 10)
plt.legend(); plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title(f'L1 Regularization (rate={L1_RATE})')
plt.show()

"""### 3. Experiment B. L2 Regularization"""

from keras.regularizers import l2

L2_RATE = 0.001

model_l2 = Sequential()
model_l2.add(Flatten())
model_l2.add(Dense(64, activation='relu', kernel_regularizer=l2(L2_RATE)))
model_l2.add(Dense(10, activation='softmax', kernel_regularizer=l2(L2_RATE)))
model_l2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

history_l2 = model_l2.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_l2.summary()

loss, acc = model_l2.evaluate(X_test, y_test)

print('Akurasi Testing L2:', acc)

plt.plot(range(1, len(history_l2.history['loss']) + 1),
         history_l2.history['loss'], 'r', label='training loss')

plt.plot(range(1, len(history_l2.history['val_loss']) + 1),
         history_l2.history['val_loss'], 'b', label='validation loss')

plt.xticks(range(1, 11))
plt.xlim(1, 10)

plt.legend()
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title(f'L2 Regularization (rate={L2_RATE})')

plt.show()

"""### 5. Experiment C. Dropout"""

from keras.layers import Dropout

DROPOUT_RATE = 0.3

model_do = Sequential()
model_do.add(Flatten())
model_do.add(Dense(64, activation='relu'))
model_do.add(Dropout(DROPOUT_RATE))
model_do.add(Dense(10, activation='softmax'))
model_do.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

history_do = model_do.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_do.summary()

loss, acc = model_do.evaluate(X_test, y_test)

print('Akurasi Testing Dropout:', acc)

plt.plot(range(1, len(history_do.history['loss']) + 1),
         history_do.history['loss'], 'r', label='training loss')

plt.plot(range(1, len(history_do.history['val_loss']) + 1),
         history_do.history['val_loss'], 'b', label='validation loss')

plt.xticks(range(1, 11))
plt.xlim(1, 10)

plt.legend()
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title(f'Dropout (rate={DROPOUT_RATE})')

plt.show()

"""### 6. Experiment D. Early Stopping"""

from keras.callbacks import EarlyStopping

model_es = Sequential()
model_es.add(Flatten())
model_es.add(Dense(64, activation='relu'))
model_es.add(Dense(10, activation='softmax'))
model_es.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

es_cb = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)
history_es = model_es.fit(X_train, y_train, epochs=50, batch_size=100,
                           validation_data=(X_test, y_test), callbacks=[es_cb])
model_es.summary()

loss, acc = model_es.evaluate(X_test, y_test)

print('Akurasi Testing Early Stopping:', acc)

print('Jumlah epoch yang benar-benar berjalan:', len(history_es.history['loss']))

plt.plot(range(1, len(history_es.history['loss']) + 1),
         history_es.history['loss'], 'r', label='training loss')

plt.plot(range(1, len(history_es.history['val_loss']) + 1),
         history_es.history['val_loss'], 'b', label='validation loss')

plt.xticks(range(1, len(history_es.history['loss']) + 1))
plt.xlim(1, len(history_es.history['loss']))

plt.legend()
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Early Stopping (patience=2)')

plt.show()

"""### 7. Experiment E. L1 Regularization + Dropout"""

model_l1do = Sequential()
model_l1do.add(Flatten())
model_l1do.add(Dense(64, activation='relu', kernel_regularizer=l1(L1_RATE)))
model_l1do.add(Dropout(DROPOUT_RATE))
model_l1do.add(Dense(10, activation='softmax', kernel_regularizer=l1(L1_RATE)))
model_l1do.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

history_l1do = model_l1do.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_l1do.summary()

loss, acc = model_l1do.evaluate(X_test, y_test)

print('Akurasi Testing L1+Dropout:', acc)

plt.plot(range(1, len(history_l1do.history['loss']) + 1),
         history_l1do.history['loss'], 'r', label='training loss')

plt.plot(range(1, len(history_l1do.history['val_loss']) + 1),
         history_l1do.history['val_loss'], 'b', label='validation loss')

plt.xticks(range(1, 11))
plt.xlim(1, 10)

plt.legend()
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('L1 + Dropout')

plt.show()